### ISSUE TITLE
update the search provider to offer a dbus service, or allow users to disable it in settings

### ISSUE THREAD

**Issue by kparal** [philn/gnome-shell-gajim-extension#20]
I wanted to disable the Gajim contact search provider (I don't like it), so I went to gnome control center -> Search, but Gajim wasn't listed there. So I filed a bug against GNOME:

https://bugzilla.gnome.org/show_bug.cgi?id=741714

But according to GNOME developers, the problem is in Gajim extension using an outdated approach in implementing the search provider. The extension should offer a dbus service and then the search provider will be configurable in control center.

Can you please either update the search provider to use a dbus service, or allow users to disable the contact search provider in extension settings?

Thanks!

**Comment by philn** [comment]
Thanks Kamil for the bug report, I'll try to migrate the search provider to DBus soon!

**Comment by philn** [comment]
Well this is not possible, despite what you were told. Currently the search providers are loaded from files stored in the system data dirs and extensions obviously cannot store files there.

So unless the GNOME developers are willing to add support for extensions providing DBus SearchProvider2 services I can't do anything about this issue.

**Comment by kparal** [comment]
Thanks for info, @philn. Could you please explain in detail what the problem is in that bugzilla ticket linked in the description? I'll then reopen the bug. Let's have GNOME developers either recommend a different approach or implement some solution. Thank you!

**Comment by philn** [comment]
I'm closing this then, as per upstream bug above.

**Comment by kparal** [comment]
According to [Bastien's latest response](https://bugzilla.gnome.org/show_bug.cgi?id=741714#c6), it seems that the only possible way is for gnome-shell-gajim-extension to provide a search configuration in its own extension settings. Sorry for the initial confusion.
