### ISSUE TITLE
Support for Gnome 3.18

### ISSUE THREAD

**Issue by szpak** [philn/gnome-shell-gajim-extension#22]
It would be useful to have it supported.

**Comment by philn** [comment]
2.18? :)

**Comment by szpak** [comment]
Yup, I put it in the summary :).

**Comment by philn** [comment]
You mean 3.18 I suppose. Do you feel like starting a patch? I actually don't use Gajim much anymore.

**Comment by szpak** [comment]
Aaaaa, sure 3.18 :). The bad is that I really don't like JavaScript... We will see how much desperate I will ;).

**Comment by philn** [comment]
Try to update the version in metadata.json and cross fingers.

**Comment by timodenissen** [comment]
philn, I did and it didn't work for me (Gnome 3.18.4-1 from Debian)

**Comment by philn** [comment]
Weird, looks like glib-compile-schemas wasn't invoked by dist.py ?

**Comment by timodenissen** [comment]
I ran dist.py again, now I can open the settings dialog. Can confirm a change of the version number in the metadata makes the extension installable and usable with Gnome 3.18. Though the notifications look not as I expected them to look like (Contact name (and avatar) instead of the account that was messaged).

**Comment by philn** [comment]
Can you post a screenshot? Thanks for testing this BTW, much appreciated!

**Comment by djmaze** [comment]
Just tried upping the version number for Gnome 3.20. Works for me and looks ok.

**Comment by philn** [comment]
Nice, thanks @djmaze ! I'll prepare a new release then :)

**Comment by chrisnew** [comment]
*bump* anything new? :)

**Comment by philn** [comment]
Oops this one slipped off my mind, I'll try to cut a release tonight!

**Comment by philn** [comment]
It's uploaded on extensions.gnome.org too but it might be waiting for review, not sure.
